name: deepmirror_ml_task
channels:
  - conda-forge
dependencies:
  - python=3.11
  - rdkit
  - autogluon
  - pip
  - pip:
      - dimorphite-dl>=1.3.2
      - mordred>=1.2.0
      - torch
      - chemprop>=2.2.0
      - lightgbm
      - xgboost
      - auto-sklearn2
      - scikit-learn
      - scipy
      - umap-learn
      - pytest>=8.0
